### ISSUE TITLE
selecting containers when using i3

### ISSUE THREAD

**Issue by pabra** [vain/multipass#1]
I'm using i3 window manager and multipass seems to select just the wrapping container instead of the actual application. 

I selected the 3 windows at the bottom (from left to right: xev, leafpad, xfce4-terminal). No application receives any key stroke.
![2017-03-08_105636](https://cloud.githubusercontent.com/assets/3512955/23699177/7cabfb9c-03ee-11e7-9890-69c7a3460856.png)

**Comment by vain** [comment]
Ouch, I bet that's a reparenting issue. I'll look into it.

**Comment by vain** [comment]
I had a look at the source code of `xwininfo`. Of course, dealing with reparenting (and possibly multiple reparenting and what not) is not an easy task. Finding the "correct" window takes about 300 lines in `xwininfo`. Meh.

I tried to simplify that procedure. I added code that looks for the first child window with a `WM_STATE` property. This is usually the actual client window and not some decoration.

I tested this with i3, Openbox and Compiz/Unity. Appears to work. Would you mind giving the current git master a try?

I hope this works well enough. I'd really like to avoid adding hundreds of lines of code, just to find the correct window. :/

**Comment by pabra** [comment]
Thanks. Works perfectly for me now.
